---
- name: Add repository for Adoptium
  yum_repository:
    name: Adoptium
    description: Adoptium
    baseurl: "https://packages.adoptium.net/artifactory/rpm/centos/\
              {{ rh_dist_repo_version }}/x86_64"
    enabled: true
    gpgcheck: true
    gpgkey: https://packages.adoptium.net/artifactory/api/gpg/key/public

- name: Install java packages
  yum:
    name: '{{ (transport == "repositories") | ternary(jdk_package, java_artifact) }}'
    state: present
  register: package_install
  until: package_install is succeeded
