---
name: CI
'on':
  pull_request:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install test dependencies.
        run: pip3 install --upgrade ansible==2.9.* docker molecule==2.22

      - name: Install ansible-lint.
        run: pip3 install --upgrade ansible-lint==4.2.0

      - name: Run yamllint tests.
        run: yamllint . -c .yamllint

      - name: Run ansible-lint tests.
        run: ansible-lint . -c .ansible-lint

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.5, 3.7, 3.8]
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install test dependencies.
        run: pip3 install --upgrade ansible==2.9.* docker molecule==2.22

      - name: Install ansible-lint.
        run: pip3 install --upgrade ansible-lint==4.2.0

      - name: Run Molecule tests.
        run: molecule test -s default
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          ANSIBLE_LIBRARY: ~/.ansible/plugins/modules
